import type { GlobalConfig } from "payload";

export const FundMuseum: GlobalConfig = {
  slug: "fund-museum",
  label: "Фонд — Музей",
  admin: { group: "Страницы" },
  access: { read: () => true },
  fields: [
    { name: "title", type: "text", required: true, label: "Заголовок" },
    { name: "address", type: "text", required: true, label: "Адрес" },
    { name: "entryNote", type: "text", required: true, label: "Примечание (вход)" },
    {
      name: "photo1",
      type: "upload",
      relationTo: "media",
      required: true,
      label: "Фото 1",
    },
    { name: "photo1Caption", type: "text", required: true, label: "Подпись фото 1" },
    {
      name: "photo2",
      type: "upload",
      relationTo: "media",
      required: true,
      label: "Фото 2",
    },
    { name: "photo2Caption", type: "text", required: true, label: "Подпись фото 2" },
    {
      name: "scheduleDays",
      type: "text",
      required: true,
      label: "Дни работы",
    },
    {
      name: "scheduleHours",
      type: "text",
      required: true,
      label: "Часы работы",
    },
    { name: "marineTitle", type: "text", required: true, label: "Блок 1 — заголовок" },
    { name: "marineText", type: "textarea", required: true, label: "Блок 1 — текст" },
    { name: "artTitle", type: "text", required: true, label: "Блок 2 — заголовок" },
    { name: "artText", type: "textarea", required: true, label: "Блок 2 — текст" },
    { name: "historyTitle", type: "text", required: true, label: "История — заголовок" },
    {
      name: "historyLeft",
      type: "array",
      label: "История — левая колонка",
      fields: [{ name: "text", type: "textarea", required: true, label: "Абзац" }],
    },
    {
      name: "historyRight",
      type: "array",
      label: "История — правая колонка",
      fields: [{ name: "text", type: "textarea", required: true, label: "Абзац" }],
    },
    {
      name: "historyHighlightTitle",
      type: "text",
      required: true,
      label: "Синий блок — заголовок",
    },
    {
      name: "historyHighlightText",
      type: "textarea",
      required: true,
      label: "Синий блок — текст",
    },
    {
      name: "exhibitsTitle",
      type: "text",
      required: true,
      label: "Действующие экспонаты — заголовок",
    },
    {
      name: "exhibitsParagraphs",
      type: "array",
      label: "Действующие экспонаты — абзацы",
      fields: [{ name: "text", type: "textarea", required: true, label: "Абзац" }],
    },
    {
      name: "artSectionTitle",
      type: "text",
      required: true,
      label: "Художественный раздел — заголовок",
    },
    {
      name: "artSectionText",
      type: "textarea",
      required: true,
      label: "Художественный раздел — текст",
    },
    {
      name: "heritageTitle",
      type: "text",
      required: true,
      label: "Живописное наследие — заголовок",
    },
    {
      name: "heritageMain",
      type: "textarea",
      required: true,
      label: "Живописное наследие — основной текст",
    },
    {
      name: "heritageAsideLabel",
      type: "text",
      required: true,
      label: "Живописное наследие — подпись боковика",
    },
    {
      name: "heritageAside",
      type: "textarea",
      required: true,
      label: "Живописное наследие — боковой текст",
    },
    {
      name: "curatorLabel",
      type: "text",
      required: true,
      label: "Руководитель — метка",
    },
    { name: "curatorName", type: "text", required: true, label: "Руководитель — ФИО" },
    {
      name: "curatorNote",
      type: "text",
      required: true,
      label: "Руководитель — примечание",
    },
    { name: "footerText", type: "text", required: true, label: "Подвал" },
  ],
};
