name: Deploy to VPS

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Prepare Server Folders
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /var/www/sevcrf
            # Очищаем папку перед новым деплоем, кроме папки node_modules (для скорости)
            find /var/www/sevcrf -maxdepth 1 ! -name 'node_modules' ! -name '.' -exec rm -rf {} +

      - name: Copy Files to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Копируем билд, конфиги и файлы запуска
          source: ".next,public,package.json,package-lock.json,next.config.ts"
          target: "/var/www/sevcrf"

      - name: Start Application via PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/sevcrf
            npm install --production
            # Перезапускаем или создаем процесс в PM2
            pm2 delete sevcrf || true
            pm2 start npm --name "sevcrf" -- start
            pm2 save